spring.application.name=facturacion-prod

spring.datasource.url = jdbc:mysql://localhost:3306/facturacionproductos
spring.datasource.username = root

spring.jpa.hibernate.ddl-auto=update

#spring.jpa.hibernate.ddl-auto=none
#spring.sql.init.schema-locations=classpath:sql/custom-data.sql
#spring.sql.init.mode=always

spring.jpa.show-sql= true

#SEGURIDAD
spring.security.user.name=user
spring.security.user.password=programafacturacion01